version: "3.8"

services:
  pgreyes:
    image: pgreyes:1.0.1
    build: .
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgreyes.entrypoints=http"
        - "traefik.http.routers.pgreyes.rule=Host(`pgreyes.byronrm.com`)"
        - "traefik.http.middlewares.pgreyes-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.pgreyes.middlewares=pgreyes-https-redirect"
        - "traefik.http.routers.pgreyes-secure.entrypoints=https"
        - "traefik.http.routers.pgreyes-secure.rule=Host(`pgreyes.byronrm.com`)"
        - "traefik.http.routers.pgreyes-secure.tls=true"
        - "traefik.http.routers.pgreyes-secure.tls.certresolver=http"
        - "traefik.http.routers.pgreyes-secure.service=pgreyes"
        - "traefik.http.services.pgreyes.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true